package storageview

import "strings"

func PermissionsForPath(pathValue string) (permissions string, writable bool, reason string) {
	pathValue = strings.Trim(strings.ReplaceAll(pathValue, "\\", "/"), "/")
	switch {
	case pathValue == "main/Documents" || strings.HasPrefix(pathValue, "main/Documents/"):
		return PermissionWritable, true, ""
	case pathValue == "main/Notes" || strings.HasPrefix(pathValue, "main/Notes/"):
		return PermissionReadOnly, false, "LOOM notes projection entries are generated from authoritative notes sources."
	case pathValue == "main/Archive" || strings.HasPrefix(pathValue, "main/Archive/"):
		return PermissionControlled, false, "Archive changes must go through LOOM archive operations."
	case pathValue == "_System" || strings.HasPrefix(pathValue, "_System/"):
		return PermissionReadOnly, false, "System entries are generated by LOOM."
	case strings.HasPrefix(strings.ToLower(pathValue), "backups/") || strings.Contains(pathValue, "/Backups") || strings.Contains(pathValue, "/Backups/"):
		return PermissionReadOnly, false, "Backups are created by node folder watching and retention policy."
	case strings.Contains(pathValue, "/Dropzone") || strings.Contains(pathValue, "/Dropzone/"):
		return PermissionReadOnly, false, "Dropzone entries are custody records accepted by main."
	case strings.Contains(pathValue, "/Lane") || strings.Contains(pathValue, "/Lane/"):
		return PermissionReadOnly, false, "Lane entries are custody records accepted by main."
	default:
		return PermissionReadOnly, false, "Catalog entries are read-only unless an owning storage workflow explicitly permits changes."
	}
}
