package httpapi

import (
	"bytes"
	"crypto/sha256"
	"database/sql"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"loom.local/loom/internal/ids"
	"loom.local/loom/internal/localclient"
	"loom.local/loom/internal/loomcli"
	pc "loom.local/loom/internal/projectcontracts"
	"loom.local/loom/internal/projectregistration"
	"loom.local/loom/internal/projects"
	"loom.local/loom/internal/requestctx"
	"loom.local/loom/internal/setup"
)

// The source and expected state are independent raw inputs, not generated by
// the migration producer. The ordinary validator/registration owner seeds DB.
func migrationHTTPFixture(t *testing.T, db *sql.DB, box, version string) (string, string, []byte) {
	t.Helper()
	id := ids.NewProjectID()
	root := filepath.Join(box, "fixture-"+version)
	if err := os.MkdirAll(filepath.Join(root, ".loom"), 0700); err != nil {
		t.Fatal(err)
	}
	raw := []byte(fmt.Sprintf("kind: loom.project\nschema_version: project.contract.v%s\nproject:\n  id: %s\n  slug: fixture-%s\n  name: Conversion fixture\n  owner_node: main\n  status: active\n", version, id, strings.ReplaceAll(version, ".", "-")))
	if version == "0.3" {
		raw = []byte(strings.ReplaceAll(string(raw), "  id: "+id+"\n", ""))
	}
	if version == "0.5" {
		raw = append(raw, []byte("resources: {}\n")...)
	}
	if err := os.WriteFile(filepath.Join(root, pc.CanonicalRootContractPath), raw, 0600); err != nil {
		t.Fatal(err)
	}
	analysis := pc.Analyze(root)
	input, err := projectregistration.BuildInput(analysis, "migration-fixture")
	if err != nil {
		t.Fatalf("seed %s: %v %+v", version, err, analysis.Report)
	}
	req, err := requestctx.ResolveBootstrap(t.Context(), db, "migration-fixture")
	if err != nil {
		t.Fatal(err)
	}
	result, err := projects.NewService(db).RegisterProjectContract(t.Context(), req, input)
	if err != nil {
		t.Fatal(err)
	}
	return result.Detail.Project.Project.ProjectID, root, raw
}
func migrationCLIManifest(t *testing.T, url string) string {
	t.Helper()
	dir := t.TempDir()
	file := filepath.Join(dir, "install.yaml")
	if err := setup.WriteManifest(file, setup.InstallManifest{SchemaVersion: setup.ManifestSchemaVersion, NodeKey: "fixture-client", NodeID: ids.NewNodeID(), NodeKind: "workspace", NodeRole: "primary_workspace", RuntimeClass: "workspace_full", MainURL: url, DataDir: filepath.Join(dir, "data"), BoxPath: filepath.Join(dir, "box"), BoxProfile: "workspace", MigrationsDir: "migrations", BootstrapMode: "none", ObjectStorePath: filepath.Join(dir, "data/object-store"), MainDocumentsPath: filepath.Join(dir, "data/main-documents"), StorageExportRoot: filepath.Join(dir, "data/storage-views/main-export")}); err != nil {
		t.Fatal(err)
	}
	return file
}
func TestDeclarationMigrationRegisteredHTTPPostgres(t *testing.T) {
	db := declarationHTTPDatabase(t)
	box := t.TempDir()
	server := declarationOwnedServer(t, db, box, nil)
	client, _ := localclient.NewHTTP(server.URL)
	manifest := migrationCLIManifest(t, server.URL)
	for _, version := range []string{"0.3", "0.4", "0.5"} {
		t.Run(version, func(t *testing.T) {
			id, root, raw := migrationHTTPFixture(t, db, box, version)
			before := declarationDBSnapshot(t, db)
			env, err := client.GetProjectConversionAssessment(t.Context(), "migration-positive", id, "main")
			if err != nil {
				t.Fatal(err)
			}
			a := env.Data
			want := "eligible"
			if version == "0.5" {
				want = "already_declaration"
			}
			if a.State != want {
				t.Fatalf("state %s want %s: %+v preview=%+v", a.State, want, a.Issues, a.Preview.Issues)
			}
			if a.ProjectID != id || a.OwnerNode != "main" || !pc.ValidDeclarationMigrationAssessment(a) {
				t.Fatalf("invalid assessment: %+v", a)
			}
			expected := fmt.Sprintf("sha256:%x", sha256.Sum256(raw))
			found := false
			for _, s := range a.Preview.Sources {
				if s.Ref == pc.CanonicalRootContractPath {
					found = s.Digest == expected
				}
			}
			if !found {
				t.Fatal("original source digest missing")
			}
			if version != "0.5" {
				if a.Preview.Candidate == nil || !strings.Contains(a.Preview.Candidate.YAML, id) || a.Preview.Retention.Publication != "not_performed" {
					t.Fatalf("candidate/retention %+v", a.Preview)
				}
			}
			data, _ := json.Marshal(a)
			if bytes.Contains(data, []byte(root)) || bytes.Contains(data, []byte(box)) {
				t.Fatal("host path leaked")
			}
			for _, asJSON := range []bool{true, false} {
				cmd := loomcli.NewRootCommand()
				var out, stderr bytes.Buffer
				cmd.SetOut(&out)
				cmd.SetErr(&stderr)
				args := []string{"--config", manifest, "project", "status", id, "--conversion-preview"}
				if asJSON {
					args = append(args, "--json")
				}
				cmd.SetArgs(args)
				if err := cmd.ExecuteContext(t.Context()); err != nil {
					t.Fatalf("CLI %s %v", stderr.String(), err)
				}
				if asJSON {
					var got pc.DeclarationMigrationAssessment
					if json.Unmarshal(out.Bytes(), &got) != nil || got.State != want {
						t.Fatalf("CLI %s", out.String())
					}
				} else if !strings.Contains(out.String(), "Conversion assessment: "+want) || strings.Contains(out.String(), "loom project apply") {
					t.Fatalf("human %s", out.String())
				}
				if strings.Contains(out.String(), root) {
					t.Fatal("CLI path leaked")
				}
			}
			if version == "0.5" {
				if _, err = client.GetProjectDeclarationStatus(t.Context(), "v05-control", id, "main"); err != nil {
					t.Fatalf("ordinary v05 status: %v", err)
				}
			}
			declarationAssertUnchanged(t, db, before)
			after, e := os.ReadFile(filepath.Join(root, pc.CanonicalRootContractPath))
			if e != nil || !bytes.Equal(raw, after) {
				t.Fatal("source changed")
			}
		})
	}
}
