package httpapi

import (
	"context"
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"reflect"
	"strings"

	"loom.local/loom/internal/capabilities"
	"loom.local/loom/internal/requestctx"
	"loom.local/loom/internal/response"
	"loom.local/loom/internal/storagearchive"
)

type ProjectPhysicalArchiveService interface {
	ProjectPhysicalScope(context.Context, string) (string, string, string, error)
	ReviewProjectPhysicalArchive(context.Context, requestctx.Context, string, storagearchive.ProjectPhysicalArchivePlanInput) (storagearchive.ProjectPhysicalPlanReview, error)
	ReviewProjectPhysicalRestore(context.Context, requestctx.Context, string, storagearchive.ProjectPhysicalRestorePlanInput) (storagearchive.ProjectPhysicalPlanReview, error)
	ApplyReviewedProjectPhysicalPlan(context.Context, requestctx.Context, string, storagearchive.ProjectPhysicalApplyRequest) (storagearchive.ProjectPhysicalMutationSummary, error)
	RecoverReviewedProjectPhysicalKind(context.Context, requestctx.Context, string, storagearchive.ProjectPhysicalRecoverRequest, storagearchive.WorkspaceOperationKind) (storagearchive.ProjectPhysicalMutationSummary, error)
}

func projectPhysicalArchiveRoute(path string) (string, storagearchive.WorkspaceOperationKind, string, bool) {
	parts := strings.Split(strings.TrimPrefix(path, "/v1/projects/"), "/")
	if !strings.HasPrefix(path, "/v1/projects/") || len(parts) < 3 || parts[0] == "" || parts[1] != "archive" {
		return "", "", "", false
	}
	kind, action := storagearchive.WorkspaceOperationArchive, parts[len(parts)-1]
	if len(parts) == 4 && parts[2] == "restore" {
		kind = storagearchive.WorkspaceOperationRestore
	} else if len(parts) != 3 {
		return "", "", "", false
	}
	return parts[0], kind, action, action == "plan" || action == "apply" || action == "recover"
}

func (s Server) handleProjectPhysicalArchive(w http.ResponseWriter, r *http.Request, ref string, kind storagearchive.WorkspaceOperationKind, action string) {
	corr, ctx, cancel := workspaceArchiveRequestMeta(r)
	defer cancel()
	fail := func(code string, status int) { s.writeProjectPhysicalFailure(w, corr, code, status, nil) }
	if r.Method != http.MethodPost {
		fail("method_not_allowed", http.StatusMethodNotAllowed)
		return
	}
	service := s.services.ProjectPhysicalArchive
	if service == nil {
		service = s.services.ProjectArchive
	}
	if projectArchiveDependencyNil(service) || projectArchiveDependencyNil(s.services.WorkspaceArchiveAuthorizer) {
		fail("not_ready", http.StatusServiceUnavailable)
		return
	}
	resolver := s.services.WorkspaceArchiveRequestResolver
	if resolver == nil {
		resolver = func(ctx context.Context, corr string) (requestctx.Context, error) {
			return requestctx.ResolveBootstrap(ctx, s.services.DB, corr)
		}
	}
	if s.services.WorkspaceArchiveAuthorizer == nil {
		fail("not_ready", http.StatusServiceUnavailable)
		return
	}
	req, err := resolver(ctx, corr)
	if err != nil || req.ActorID == "" || req.OriginNodeID == "" {
		fail("caller_unavailable", http.StatusForbidden)
		return
	}
	projectID, scopeID, scopeKey, err := service.ProjectPhysicalScope(ctx, ref)
	if err != nil || projectID == "" || scopeID == "" || scopeKey == "" {
		s.writeProjectPhysicalError(w, corr, err, nil)
		return
	}
	req.ScopeID, req.ScopeKey = scopeID, scopeKey
	capability := capabilities.WorkspaceArchiveApplyCapability
	if kind == storagearchive.WorkspaceOperationRestore {
		capability = capabilities.WorkspaceArchiveRestoreApplyCapability
	}
	if action == "plan" {
		capability = capabilities.WorkspaceArchivePlanCapability
		if kind == storagearchive.WorkspaceOperationRestore {
			capability = capabilities.WorkspaceArchiveRestorePlanCapability
		}
	}
	if err := s.services.WorkspaceArchiveAuthorizer.Authorize(ctx, req, capability); err != nil {
		fail("forbidden", http.StatusForbidden)
		return
	}
	if action == "recover" {
		if err := s.services.WorkspaceArchiveAuthorizer.Authorize(ctx, req, capabilities.WorkspaceArchiveRecoverCapability); err != nil {
			fail("forbidden", http.StatusForbidden)
			return
		}
	}
	decode := func(v any) bool {
		d := json.NewDecoder(http.MaxBytesReader(w, r.Body, storagearchive.MaximumWorkspaceSurfaceRequestBytes))
		d.DisallowUnknownFields()
		if err := d.Decode(v); err != nil {
			fail("invalid_request", http.StatusBadRequest)
			return false
		}
		if err := d.Decode(new(any)); !errors.Is(err, io.EOF) {
			fail("invalid_request", http.StatusBadRequest)
			return false
		}
		return true
	}
	if action == "plan" {
		// IDs and observation times are generated by the planner, not the caller.
		var input struct {
			Reason string `json:"reason"`
		}
		if !decode(&input) {
			return
		}
		var review storagearchive.ProjectPhysicalPlanReview
		if kind == storagearchive.WorkspaceOperationArchive {
			review, err = service.ReviewProjectPhysicalArchive(ctx, req, projectID, storagearchive.ProjectPhysicalArchivePlanInput{Reason: input.Reason})
		} else {
			review, err = service.ReviewProjectPhysicalRestore(ctx, req, projectID, storagearchive.ProjectPhysicalRestorePlanInput{Reason: input.Reason})
		}
		if err != nil {
			s.writeProjectPhysicalError(w, corr, err, nil)
			return
		}
		if storagearchive.ValidateProjectPhysicalPlanReview(review) != nil || review.ProjectID != projectID || review.Request != req || review.Workspace.OperationKind != kind {
			fail("invalid_review", http.StatusConflict)
			return
		}
		s.writeProjectPhysicalJSON(w, corr, http.StatusOK, response.Success(corr, review))
		return
	}
	var result storagearchive.ProjectPhysicalMutationSummary
	if action == "apply" {
		var input storagearchive.ProjectPhysicalApplyRequest
		if !decode(&input) {
			return
		}
		if !input.Confirm || input.PlanDigest == "" || input.PlanDigest != input.Plan.PlanDigest || input.Plan.Workspace.OperationKind != kind {
			fail("review_confirmation_required", http.StatusBadRequest)
			return
		}
		bound := req
		bound.CorrelationID = input.Plan.Request.CorrelationID
		if input.Plan.ProjectID != projectID || bound != input.Plan.Request {
			fail("caller_mismatch", http.StatusForbidden)
			return
		}
		if storagearchive.ValidateProjectPhysicalPlanReview(input.Plan) != nil {
			fail("invalid_review", http.StatusBadRequest)
			return
		}
		result, err = service.ApplyReviewedProjectPhysicalPlan(ctx, req, projectID, input)
	} else {
		var input storagearchive.ProjectPhysicalRecoverRequest
		if !decode(&input) {
			return
		}
		if !input.Confirm || input.OperationID == "" || input.PlanDigest == "" {
			fail("review_confirmation_required", http.StatusBadRequest)
			return
		}
		result, err = service.RecoverReviewedProjectPhysicalKind(ctx, req, projectID, input, kind)
	}
	if err != nil {
		s.writeProjectPhysicalError(w, corr, err, &result)
		return
	}
	s.writeProjectPhysicalJSON(w, corr, http.StatusOK, response.Success(corr, result))
}

func projectArchiveDependencyNil(v any) bool {
	return v == nil || (reflect.ValueOf(v).Kind() == reflect.Pointer && reflect.ValueOf(v).IsNil())
}

func (s Server) writeProjectPhysicalError(w http.ResponseWriter, corr string, err error, result *storagearchive.ProjectPhysicalMutationSummary) {
	code, status := "operation_failed", http.StatusInternalServerError
	var failure storagearchive.ProjectPhysicalSurfaceError
	if errors.As(err, &failure) {
		switch failure.Code {
		case "not_ready", "project_unavailable", "evidence_unavailable":
			code, status = failure.Code, http.StatusServiceUnavailable
		case "invalid_request", "invalid_review", "review_confirmation_required":
			code, status = failure.Code, http.StatusBadRequest
		case "caller_mismatch", "project_mismatch":
			code, status = failure.Code, http.StatusForbidden
		case "plan_unavailable", "invalid_plan", "evidence_too_large", "evidence_conflict", "restore_not_ready", "evidence_missing", "review_stale", "review_mismatch":
			code, status = failure.Code, http.StatusConflict
		}
	}
	if s.logger != nil && err != nil {
		cause := err
		if failure.Unwrap() != nil {
			cause = failure.Unwrap()
		}
		s.logger.Warn("project archive request failed", "component", "httpapi", "correlation_id", corr,
			"code", "project_archive."+code, "status", status, "cause", cause.Error())
	}
	s.writeProjectPhysicalFailure(w, corr, code, status, result)
}

func (s Server) writeProjectPhysicalFailure(w http.ResponseWriter, corr, code string, status int, result *storagearchive.ProjectPhysicalMutationSummary) {
	if result != nil && result.OperationID == "" {
		result = nil
	}
	body := struct {
		response.ErrorEnvelope
		Data *storagearchive.ProjectPhysicalMutationSummary `json:"data,omitempty"`
	}{response.ErrorEnvelope{OK: false, Meta: response.NewMeta(corr), Error: response.ErrorBody{Code: "project_archive." + code, Domain: "project_archive", Summary: "Project archive request did not complete. Inspect any returned durable phase before recovery.", CorrelationID: corr}}, result}
	s.writeProjectPhysicalJSON(w, corr, status, body)
}

func (s Server) writeProjectPhysicalJSON(w http.ResponseWriter, corr string, status int, value any) {
	data, err := json.Marshal(value)
	if err != nil || len(data)+1 > storagearchive.MaximumWorkspaceSurfaceResponseBytes {
		s.writeError(w, corr, http.StatusInternalServerError, "project_archive.output_unavailable", "project_archive", "response", "Bounded response unavailable; inspect the operation before retrying.", nil)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_, _ = w.Write(append(data, '\n'))
}
