package ids

import "testing"

func TestNewTypedIDsValidate(t *testing.T) {
	tests := []struct {
		name   string
		prefix string
		id     string
	}{
		{name: "actor", prefix: ActorPrefix, id: NewActorID()},
		{name: "actor node authorization", prefix: ActorNodeAuthorizationPrefix, id: NewActorNodeAuthorizationID()},
		{name: "node", prefix: NodePrefix, id: NewNodeID()},
		{name: "scope", prefix: ScopePrefix, id: NewScopeID()},
		{name: "event", prefix: EventPrefix, id: NewEventID()},
		{name: "project", prefix: ProjectPrefix, id: NewProjectID()},
		{name: "project contract registration", prefix: ProjectContractRegistrationPrefix, id: NewProjectContractRegistrationID()},
		{name: "project contract facet", prefix: ProjectContractFacetPrefix, id: NewProjectContractFacetID()},
		{name: "project script exposure", prefix: ProjectScriptExposurePrefix, id: NewProjectScriptExposureID()},
		{name: "project schedule registration", prefix: ProjectScheduleRegistrationPrefix, id: NewProjectScheduleRegistrationID()},
		{name: "project direct event registration", prefix: ProjectDirectEventRegistrationPrefix, id: NewProjectDirectEventRegistrationID()},
		{name: "project watched root registration", prefix: ProjectWatchedRootRegistrationPrefix, id: NewProjectWatchedRootRegistrationID()},
		{name: "project connector registration", prefix: ProjectConnectorRegistrationPrefix, id: NewProjectConnectorRegistrationID()},
		{name: "project module registration", prefix: ProjectModuleRegistrationPrefix, id: NewProjectModuleRegistrationID()},
		{name: "object", prefix: ObjectPrefix, id: NewObjectID()},
		{name: "object version", prefix: ObjectVersionPrefix, id: NewObjectVersionID()},
		{name: "blob", prefix: BlobPrefix, id: NewBlobID()},
		{name: "object scope link", prefix: ObjectScopeLinkPrefix, id: NewObjectScopeLinkID()},
		{name: "object location", prefix: ObjectLocationPrefix, id: NewObjectLocationID()},
		{name: "project membership", prefix: ProjectMembershipPrefix, id: NewProjectMembershipID()},
		{name: "project policy", prefix: ProjectPolicyPrefix, id: NewProjectPolicyID()},
		{name: "workspace view", prefix: WorkspaceViewPrefix, id: NewWorkspaceViewID()},
		{name: "extracted text", prefix: ExtractedTextPrefix, id: NewExtractedTextID()},
		{name: "document chunk", prefix: DocumentChunkPrefix, id: NewDocumentChunkID()},
		{name: "search document", prefix: SearchDocumentPrefix, id: NewSearchDocumentID()},
		{name: "index status", prefix: IndexStatusPrefix, id: NewIndexStatusID()},
		{name: "script", prefix: ScriptPrefix, id: NewScriptID()},
		{name: "script version", prefix: ScriptVersionPrefix, id: NewScriptVersionID()},
		{name: "runner", prefix: RunnerPrefix, id: NewRunnerID()},
		{name: "job", prefix: JobPrefix, id: NewJobID()},
		{name: "job attempt", prefix: JobAttemptPrefix, id: NewJobAttemptID()},
		{name: "job log", prefix: JobLogPrefix, id: NewJobLogID()},
		{name: "job output", prefix: JobOutputPrefix, id: NewJobOutputID()},
		{name: "artifact", prefix: ArtifactPrefix, id: NewArtifactID()},
		{name: "idempotency", prefix: IdempotencyPrefix, id: NewIdempotencyID()},
		{name: "admin operation", prefix: AdminOperationPrefix, id: NewAdminOperationID()},
		{name: "provider", prefix: ProviderPrefix, id: NewProviderID()},
		{name: "provider advertisement", prefix: ProviderAdvertisementPrefix, id: NewProviderAdvertisementID()},
		{name: "capability class", prefix: CapabilityClassPrefix, id: NewCapabilityClassID()},
		{name: "capability endpoint", prefix: CapabilityEndpointPrefix, id: NewCapabilityEndpointID()},
		{name: "capability endpoint version", prefix: CapabilityEndpointVersionPrefix, id: NewCapabilityEndpointVersionID()},
		{name: "capability usage document", prefix: CapabilityUsageDocumentPrefix, id: NewCapabilityUsageDocumentID()},
		{name: "policy decision", prefix: PolicyDecisionPrefix, id: NewPolicyDecisionID()},
		{name: "approval", prefix: ApprovalPrefix, id: NewApprovalID()},
		{name: "grant", prefix: GrantPrefix, id: NewGrantID()},
		{name: "route", prefix: RoutePrefix, id: NewRouteID()},
		{name: "capability call", prefix: CapabilityCallPrefix, id: NewCapabilityCallID()},
		{name: "node enrollment token", prefix: NodeEnrollmentTokenPrefix, id: NewNodeEnrollmentTokenID()},
		{name: "node enrollment request", prefix: NodeEnrollmentRequestPrefix, id: NewNodeEnrollmentRequestID()},
		{name: "node credential", prefix: NodeCredentialPrefix, id: NewNodeCredentialID()},
		{name: "node heartbeat", prefix: NodeHeartbeatPrefix, id: NewNodeHeartbeatID()},
		{name: "communication message", prefix: CommunicationMessagePrefix, id: NewCommunicationMessageID()},
		{name: "communication ack", prefix: CommunicationAckPrefix, id: NewCommunicationAckID()},
		{name: "local event", prefix: LocalEventPrefix, id: NewLocalEventID()},
		{name: "local outbox", prefix: LocalOutboxPrefix, id: NewLocalOutboxID()},
		{name: "local cursor", prefix: LocalCursorPrefix, id: NewLocalCursorID()},
		{name: "local conflict", prefix: LocalConflictPrefix, id: NewLocalConflictID()},
		{name: "local backup artifact", prefix: LocalBackupArtifactPrefix, id: NewLocalBackupArtifactID()},
		{name: "local backup batch", prefix: LocalBackupBatchPrefix, id: NewLocalBackupBatchID()},
		{name: "local backup item", prefix: LocalBackupItemPrefix, id: NewLocalBackupItemID()},
		{name: "ingested event", prefix: IngestedEventPrefix, id: NewIngestedEventID()},
		{name: "sync batch", prefix: SyncBatchPrefix, id: NewSyncBatchID()},
		{name: "sync batch item", prefix: SyncBatchItemPrefix, id: NewSyncBatchItemID()},
		{name: "sync cursor", prefix: SyncCursorPrefix, id: NewSyncCursorID()},
		{name: "sync conflict", prefix: SyncConflictPrefix, id: NewSyncConflictID()},
		{name: "replica", prefix: ReplicaPrefix, id: NewReplicaID()},
		{name: "private backup", prefix: PrivateBackupPrefix, id: NewPrivateBackupID()},
		{name: "deletion request", prefix: DeletionRequestPrefix, id: NewDeletionRequestID()},
		{name: "topic", prefix: TopicPrefix, id: NewTopicID()},
		{name: "topic publication", prefix: TopicPublicationPrefix, id: NewTopicPublicationID()},
		{name: "subscription", prefix: SubscriptionPrefix, id: NewSubscriptionID()},
		{name: "presence", prefix: PresencePrefix, id: NewPresenceID()},
		{name: "notification", prefix: NotificationPrefix, id: NewNotificationID()},
		{name: "notification delivery", prefix: NotificationDeliveryPrefix, id: NewNotificationDeliveryID()},
		{name: "progress feed", prefix: ProgressFeedPrefix, id: NewProgressFeedID()},
		{name: "progress update", prefix: ProgressUpdatePrefix, id: NewProgressUpdateID()},
		{name: "lease", prefix: LeasePrefix, id: NewLeaseID()},
		{name: "agent access session", prefix: AgentAccessSessionPrefix, id: NewAgentAccessSessionID()},
		{name: "agent work context", prefix: AgentWorkContextPrefix, id: NewAgentWorkContextID()},
		{name: "tool view", prefix: ToolViewPrefix, id: NewToolViewID()},
		{name: "tool view entry", prefix: ToolViewEntryPrefix, id: NewToolViewEntryID()},
		{name: "agent tool call", prefix: AgentToolCallPrefix, id: NewAgentToolCallID()},
		{name: "worklog entry", prefix: WorklogEntryPrefix, id: NewWorklogEntryID()},
		{name: "module package", prefix: ModulePackagePrefix, id: NewModulePackageID()},
		{name: "module version", prefix: ModuleVersionPrefix, id: NewModuleVersionID()},
		{name: "module requirement", prefix: ModuleRequirementPrefix, id: NewModuleRequirementID()},
		{name: "module declaration", prefix: ModuleDeclarationPrefix, id: NewModuleDeclarationID()},
		{name: "module namespace", prefix: ModuleNamespacePrefix, id: NewModuleNamespaceID()},
		{name: "module installation", prefix: ModuleInstallationPrefix, id: NewModuleInstallationID()},
		{name: "module health", prefix: ModuleHealthPrefix, id: NewModuleHealthID()},
		{name: "module backup export", prefix: ModuleBackupExportPrefix, id: NewModuleBackupExportID()},
		{name: "worker instance", prefix: WorkerInstancePrefix, id: NewWorkerInstanceID()},
		{name: "worker run", prefix: WorkerRunPrefix, id: NewWorkerRunID()},
		{name: "worker lease", prefix: WorkerLeasePrefix, id: NewWorkerLeaseID()},
		{name: "worker checkpoint", prefix: WorkerCheckpointPrefix, id: NewWorkerCheckpointID()},
		{name: "worker control", prefix: WorkerControlPrefix, id: NewWorkerControlID()},
		{name: "worker heartbeat", prefix: WorkerHeartbeatPrefix, id: NewWorkerHeartbeatID()},
		{name: "worker health", prefix: WorkerHealthPrefix, id: NewWorkerHealthID()},
		{name: "maintenance operation", prefix: MaintenanceOperationPrefix, id: NewMaintenanceOperationID()},
		{name: "maintenance finding", prefix: MaintenanceFindingPrefix, id: NewMaintenanceFindingID()},
		{name: "maintenance artifact", prefix: MaintenanceArtifactPrefix, id: NewMaintenanceArtifactID()},
		{name: "automation", prefix: AutomationPrefix, id: NewAutomationID()},
		{name: "schedule", prefix: SchedulePrefix, id: NewScheduleID()},
		{name: "schedule fire", prefix: ScheduleFirePrefix, id: NewScheduleFireID()},
		{name: "invocation", prefix: InvocationPrefix, id: NewInvocationID()},
		{name: "integration", prefix: IntegrationPrefix, id: NewIntegrationID()},
		{name: "integration auth profile", prefix: IntegrationAuthProfilePrefix, id: NewIntegrationAuthProfileID()},
		{name: "direct event endpoint", prefix: DirectEventEndpointPrefix, id: NewDirectEventEndpointID()},
		{name: "direct event", prefix: DirectEventPrefix, id: NewDirectEventID()},
		{name: "watched root", prefix: WatchedRootPrefix, id: NewWatchedRootID()},
		{name: "watched root finding", prefix: WatchedRootFindingPrefix, id: NewWatchedRootFindingID()},
		{name: "watched root backup batch", prefix: WatchedRootBackupBatchPrefix, id: NewWatchedRootBackupBatchID()},
		{name: "watched root backup item", prefix: WatchedRootBackupItemPrefix, id: NewWatchedRootBackupItemID()},
		{name: "storage entry", prefix: StorageEntryPrefix, id: NewStorageEntryID()},
		{name: "storage entry version", prefix: StorageEntryVersionPrefix, id: NewStorageEntryVersionID()},
		{name: "storage physical ref", prefix: StoragePhysicalRefPrefix, id: NewStoragePhysicalRefID()},
		{name: "storage view build", prefix: StorageViewBuildPrefix, id: NewStorageViewBuildID()},
		{name: "storage view entry", prefix: StorageViewEntryPrefix, id: NewStorageViewEntryID()},
		{name: "storage archive manifest", prefix: StorageArchiveManifestPrefix, id: NewStorageArchiveManifestID()},
		{name: "storage retention entry", prefix: StorageRetentionEntryPrefix, id: NewStorageRetentionEntryID()},
		{name: "storage tombstone", prefix: StorageTombstonePrefix, id: NewStorageTombstoneID()},
		{name: "storage filesystem observation", prefix: StorageFilesystemObservationPrefix, id: NewStorageFilesystemObservationID()},
		{name: "storage fidelity finding", prefix: StorageFidelityFindingPrefix, id: NewStorageFidelityFindingID()},
		{name: "project runtime archive", prefix: ProjectRuntimeArchivePrefix, id: NewProjectRuntimeArchiveID()},
		{name: "storage export root", prefix: StorageExportRootPrefix, id: NewStorageExportRootID()},
		{name: "storage export build", prefix: StorageExportBuildPrefix, id: NewStorageExportBuildID()},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if err := Validate(tt.prefix, tt.id); err != nil {
				t.Fatalf("Validate returned error: %v", err)
			}
		})
	}
}

func TestValidateRejectsWrongPrefix(t *testing.T) {
	id := NewActorID()
	if err := Validate(NodePrefix, id); err == nil {
		t.Fatal("Validate accepted id with wrong prefix")
	}
}

func TestNewTypedIDsAreUnique(t *testing.T) {
	seen := map[string]struct{}{}
	generators := []func() string{
		NewActorID,
		NewActorNodeAuthorizationID,
		NewNodeID,
		NewScopeID,
		NewEventID,
		NewProjectID,
		NewProjectContractRegistrationID,
		NewProjectContractFacetID,
		NewProjectScriptExposureID,
		NewProjectScheduleRegistrationID,
		NewProjectDirectEventRegistrationID,
		NewProjectWatchedRootRegistrationID,
		NewProjectConnectorRegistrationID,
		NewProjectModuleRegistrationID,
		NewObjectID,
		NewObjectVersionID,
		NewBlobID,
		NewObjectScopeLinkID,
		NewObjectLocationID,
		NewProjectMembershipID,
		NewProjectPolicyID,
		NewWorkspaceViewID,
		NewExtractedTextID,
		NewDocumentChunkID,
		NewSearchDocumentID,
		NewIndexStatusID,
		NewScriptID,
		NewScriptVersionID,
		NewRunnerID,
		NewJobID,
		NewJobAttemptID,
		NewJobLogID,
		NewJobOutputID,
		NewArtifactID,
		NewIdempotencyID,
		NewAdminOperationID,
		NewProviderID,
		NewProviderAdvertisementID,
		NewCapabilityClassID,
		NewCapabilityEndpointID,
		NewCapabilityEndpointVersionID,
		NewCapabilityUsageDocumentID,
		NewPolicyDecisionID,
		NewApprovalID,
		NewGrantID,
		NewRouteID,
		NewCapabilityCallID,
		NewNodeEnrollmentTokenID,
		NewNodeEnrollmentRequestID,
		NewNodeCredentialID,
		NewNodeHeartbeatID,
		NewCommunicationMessageID,
		NewCommunicationAckID,
		NewLocalEventID,
		NewLocalOutboxID,
		NewLocalCursorID,
		NewLocalConflictID,
		NewLocalBackupArtifactID,
		NewLocalBackupBatchID,
		NewLocalBackupItemID,
		NewIngestedEventID,
		NewSyncBatchID,
		NewSyncBatchItemID,
		NewSyncCursorID,
		NewSyncConflictID,
		NewReplicaID,
		NewPrivateBackupID,
		NewDeletionRequestID,
		NewTopicID,
		NewTopicPublicationID,
		NewSubscriptionID,
		NewPresenceID,
		NewNotificationID,
		NewNotificationDeliveryID,
		NewProgressFeedID,
		NewProgressUpdateID,
		NewLeaseID,
		NewAgentAccessSessionID,
		NewAgentWorkContextID,
		NewToolViewID,
		NewToolViewEntryID,
		NewAgentToolCallID,
		NewWorklogEntryID,
		NewModulePackageID,
		NewModuleVersionID,
		NewModuleRequirementID,
		NewModuleDeclarationID,
		NewModuleNamespaceID,
		NewModuleInstallationID,
		NewModuleHealthID,
		NewModuleBackupExportID,
		NewWorkerInstanceID,
		NewWorkerRunID,
		NewWorkerLeaseID,
		NewWorkerCheckpointID,
		NewWorkerControlID,
		NewWorkerHeartbeatID,
		NewWorkerHealthID,
		NewMaintenanceOperationID,
		NewMaintenanceFindingID,
		NewMaintenanceArtifactID,
		NewAutomationID,
		NewScheduleID,
		NewScheduleFireID,
		NewInvocationID,
		NewIntegrationID,
		NewIntegrationAuthProfileID,
		NewDirectEventEndpointID,
		NewDirectEventID,
		NewWatchedRootID,
		NewWatchedRootFindingID,
		NewWatchedRootBackupBatchID,
		NewWatchedRootBackupItemID,
		NewStorageEntryID,
		NewStorageEntryVersionID,
		NewStoragePhysicalRefID,
		NewStorageViewBuildID,
		NewStorageViewEntryID,
		NewStorageArchiveManifestID,
		NewStorageRetentionEntryID,
		NewStorageTombstoneID,
		NewProjectRuntimeArchiveID,
		NewStorageExportRootID,
		NewStorageExportBuildID,
	}

	for _, generate := range generators {
		for range 25 {
			id := generate()
			if _, ok := seen[id]; ok {
				t.Fatalf("duplicate id generated: %s", id)
			}
			seen[id] = struct{}{}
		}
	}
}

func TestValidateRejectsInvalidULID(t *testing.T) {
	if err := Validate(ProjectPrefix, "project_not-a-ulid"); err == nil {
		t.Fatal("Validate accepted invalid ULID")
	}
}
