package filesystemconnector

import (
	"encoding/json"
	"errors"
	"strings"

	"loom.local/loom/internal/capabilities"
)

type ProviderManifestInput struct {
	ScopeSegment string
	NodeKey      string
	NodeID       string
	DisplayName  string
	RuntimeClass string
	Version      string
	Config       Config
}

func BuildProvider(input ProviderManifestInput) (capabilities.AdvertisedProvider, error) {
	config := NormalizeConfig(input.Config)
	if err := ValidateConfig(config); err != nil {
		return capabilities.AdvertisedProvider{}, err
	}
	availableRoots := AvailableSafeRoots(config)
	if len(availableRoots) == 0 {
		return capabilities.AdvertisedProvider{}, errors.New("filesystem connector requires at least one non-private safe root")
	}

	version := strings.TrimSpace(input.Version)
	if version == "" {
		version = "0.1.0"
	}
	nodeKey := strings.TrimSpace(input.NodeKey)
	scopeSegment := NormalizeAddressSegment(input.ScopeSegment)
	if scopeSegment == "" {
		scopeSegment = NormalizeAddressSegment(nodeKey)
	}
	displayName := strings.TrimSpace(input.DisplayName)
	if displayName == "" {
		displayName = nodeKey
	}
	runtimeClass := strings.TrimSpace(input.RuntimeClass)
	if runtimeClass == "" {
		runtimeClass = "workspace"
	}

	providerAddress := "workspace/" + scopeSegment + "@" + ProviderKey
	rootSummaries := summariesForRoots(availableRoots)
	privateRootCount, disabledRootCount := rootVisibilityCounts(config.SafeRoots)

	return capabilities.AdvertisedProvider{
		ProviderKey:    ProviderKey,
		CompactAddress: providerAddress,
		DisplayName:    displayName + " Filesystem Connector",
		Description:    "LOOM-owned connector exposing approved safe-root filesystem operations from this workspace node.",
		ProviderType:   capabilities.ProviderTypeConnector,
		Version:        version,
		RuntimeProfileJSON: mustJSON(map[string]any{
			"agent":                          "loom-node-agent",
			"connector":                      ProviderKey,
			"runtime_class":                  runtimeClass,
			"remote_execution_enabled":       true,
			"safe_root_count":                len(availableRoots),
			"private_backup_only_root_count": privateRootCount,
			"disabled_root_count":            disabledRootCount,
			"safe_roots":                     rootSummaries,
			"absolute_paths_exposed":         false,
		}),
		DocumentationRefsJSON: json.RawMessage(`[]`),
		Health: capabilities.ProviderHealthInput{
			HealthStatus:       capabilities.HealthStatusOK,
			AvailabilityStatus: capabilities.AvailabilityStatusAvailable,
			Message:            "filesystem connector advertisement generated by loom-node-agent",
			DetailsJSON: mustJSON(map[string]any{
				"node_key":                       nodeKey,
				"node_id":                        input.NodeID,
				"safe_root_count":                len(availableRoots),
				"private_backup_only_root_count": privateRootCount,
				"disabled_root_count":            disabledRootCount,
				"safe_roots":                     rootSummaries,
			}),
		},
		Capabilities: []capabilities.AdvertisedCapability{
			safeListCapability(providerAddress, version, rootSummaries, privateRootCount),
			readMetadataCapability(providerAddress, version, rootSummaries, privateRootCount),
			ingestFileCapability(providerAddress, version, rootSummaries, privateRootCount),
		},
		UsageDocuments: []capabilities.AdvertisedUsageDocument{
			{
				Title:        "Workspace filesystem connector safe-root model",
				VersionLabel: version,
				BodyFormat:   capabilities.UsageDocumentFormatMarkdown,
				Body: strings.TrimSpace(`
Use this provider when an actor needs controlled filesystem access on the workspace node that owns the files.

Callers must use a configured root key plus a relative path. They must not send absolute paths. The connector advertises only approved safe roots and does not expose private backup-only roots.

The connector intentionally does not provide destructive operations, whole-machine scans, arbitrary recursive backup, or direct node-to-node file transfer.
`),
			},
		},
		Metadata: mustJSON(map[string]any{
			"source":                 "loom-node-agent",
			"connector":              ProviderKey,
			"node_key":               nodeKey,
			"node_id":                input.NodeID,
			"slice":                  "13_part_1",
			"execution":              "remote_node_agent",
			"remote_calls":           true,
			"absolute_paths_exposed": false,
		}),
	}, nil
}

func NormalizeAddressSegment(value string) string {
	value = strings.ToLower(strings.TrimSpace(value))
	var builder strings.Builder
	for _, r := range value {
		switch {
		case r >= 'a' && r <= 'z':
			builder.WriteRune(r)
		case r >= '0' && r <= '9':
			builder.WriteRune(r)
		case r == '-' || r == '_':
			builder.WriteRune(r)
		default:
			builder.WriteRune('-')
		}
	}
	out := strings.Trim(builder.String(), "-_")
	if out == "" {
		return ""
	}
	if out[0] < 'a' || out[0] > 'z' {
		out = "node-" + out
	}
	return out
}

func safeListCapability(providerAddress, version string, roots []SafeRootSummary, privateRootCount int) capabilities.AdvertisedCapability {
	return capabilities.AdvertisedCapability{
		EndpointName:                EndpointSafeList,
		CompactAddress:              providerAddress + "." + EndpointSafeList,
		ClassNamespace:              ConnectorNamespace,
		ClassName:                   EndpointSafeList,
		DisplayName:                 "Safe List",
		Description:                 "List entries under an approved safe root without exposing absolute filesystem paths.",
		Form:                        capabilities.CapabilityFormQuery,
		InputSchemaJSON:             json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"root":{"type":"string","description":"Configured safe root key."},"path":{"type":"string","default":".","description":"Relative path inside the safe root."},"max_entries":{"type":"integer","minimum":1,"maximum":200,"default":50},"include_hidden":{"type":"boolean","default":false}},"required":["root"]}`),
		OutputSchemaJSON:            json.RawMessage(`{"type":"object","properties":{"root":{"type":"string"},"path":{"type":"string"},"entries":{"type":"array","items":{"type":"object","properties":{"name":{"type":"string"},"relative_path":{"type":"string"},"kind":{"type":"string"},"size_bytes":{"type":"integer"},"modified_at":{"type":"string"},"hidden":{"type":"boolean"}}}},"truncated":{"type":"boolean"}}}`),
		RiskLevel:                   capabilities.RiskLevelLow,
		ExecutionAuthorizationLevel: 1,
		SideEffectsJSON:             json.RawMessage(`{"side_effects":[]}`),
		PolicyRequirementsJSON:      json.RawMessage(`{"requires_main_routing":true}`),
		ApprovalRequirementsJSON:    json.RawMessage(`{"owner_provider_review_required":true}`),
		VersionLabel:                version,
		ManifestJSON:                filesystemManifestJSON(EndpointSafeList, "remote_node", roots, privateRootCount),
		UsageDocuments: []capabilities.AdvertisedUsageDocument{
			{
				Title:        "Use filesystem.safe_list to inspect approved safe root contents",
				VersionLabel: version,
				BodyFormat:   capabilities.UsageDocumentFormatMarkdown,
				Body:         "Use `safe_list` when an actor needs to inspect the immediate contents of an approved safe root before choosing a file. Pass a root key and a relative path. The response returns relative paths only and never returns arbitrary absolute paths.",
			},
		},
		Metadata: endpointMetadata(EndpointSafeList),
	}
}

func readMetadataCapability(providerAddress, version string, roots []SafeRootSummary, privateRootCount int) capabilities.AdvertisedCapability {
	return capabilities.AdvertisedCapability{
		EndpointName:                EndpointReadMetadata,
		CompactAddress:              providerAddress + "." + EndpointReadMetadata,
		ClassNamespace:              ConnectorNamespace,
		ClassName:                   EndpointReadMetadata,
		DisplayName:                 "Read File Metadata",
		Description:                 "Read non-content metadata for one approved relative path inside a safe root.",
		Form:                        capabilities.CapabilityFormQuery,
		InputSchemaJSON:             json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"root":{"type":"string","description":"Configured safe root key."},"path":{"type":"string","description":"Relative file or directory path inside the safe root."}},"required":["root","path"]}`),
		OutputSchemaJSON:            json.RawMessage(`{"type":"object","properties":{"root":{"type":"string"},"path":{"type":"string"},"kind":{"type":"string"},"size_bytes":{"type":"integer"},"modified_at":{"type":"string"},"hidden":{"type":"boolean"},"ingest_allowed":{"type":"boolean"}}}`),
		RiskLevel:                   capabilities.RiskLevelLow,
		ExecutionAuthorizationLevel: 1,
		SideEffectsJSON:             json.RawMessage(`{"side_effects":[]}`),
		PolicyRequirementsJSON:      json.RawMessage(`{"requires_main_routing":true}`),
		ApprovalRequirementsJSON:    json.RawMessage(`{"owner_provider_review_required":true}`),
		VersionLabel:                version,
		ManifestJSON:                filesystemManifestJSON(EndpointReadMetadata, "remote_node", roots, privateRootCount),
		UsageDocuments: []capabilities.AdvertisedUsageDocument{
			{
				Title:        "Use filesystem.read_metadata to check a single approved file before ingest",
				VersionLabel: version,
				BodyFormat:   capabilities.UsageDocumentFormatMarkdown,
				Body:         "Use `read_metadata` before ingesting a file when an actor needs to verify file kind, size, and relative path. The connector enforces root plus relative path addressing and does not return file contents.",
			},
		},
		Metadata: endpointMetadata(EndpointReadMetadata),
	}
}

func ingestFileCapability(providerAddress, version string, roots []SafeRootSummary, privateRootCount int) capabilities.AdvertisedCapability {
	return capabilities.AdvertisedCapability{
		EndpointName:                EndpointIngestFile,
		CompactAddress:              providerAddress + "." + EndpointIngestFile,
		ClassNamespace:              ConnectorNamespace,
		ClassName:                   EndpointIngestFile,
		DisplayName:                 "Ingest File",
		Description:                 "Import one approved local file into the main LOOM object store through the node-agent sync/object upload path.",
		Form:                        capabilities.CapabilityFormCommand,
		InputSchemaJSON:             json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"root":{"type":"string","description":"Configured safe root key."},"path":{"type":"string","description":"Relative file path inside the safe root."},"project":{"type":"string","description":"Optional project key or ref for the created object."},"scope":{"type":"string","description":"Optional scope key or ref when project is not provided."},"name":{"type":"string","description":"Optional object display name."},"index_policy":{"type":"string","enum":["default","skip_text","skip_all","none","metadata_only","text_later","semantic_later","private_no_index"],"default":"default"}},"required":["root","path"]}`),
		OutputSchemaJSON:            json.RawMessage(`{"type":"object","properties":{"object_id":{"type":"string"},"object_version_id":{"type":"string"},"blob_id":{"type":"string"},"hash_uri":{"type":"string"},"index_status":{"type":"string"},"sync_batch_id":{"type":"string"},"replica_id":{"type":"string"}}}`),
		RiskLevel:                   capabilities.RiskLevelMedium,
		ExecutionAuthorizationLevel: 2,
		SideEffectsJSON:             json.RawMessage(`{"side_effects":["reads one approved local file","uploads selected content to main object store","creates object, version, blob, location, and replica records on main when executed"]}`),
		PolicyRequirementsJSON:      json.RawMessage(`{"requires_main_routing":true}`),
		ApprovalRequirementsJSON:    json.RawMessage(`{"owner_provider_review_required":true}`),
		VersionLabel:                version,
		ManifestJSON:                filesystemManifestJSON(EndpointIngestFile, "remote_node_sync_object_upload", roots, privateRootCount),
		UsageDocuments: []capabilities.AdvertisedUsageDocument{
			{
				Title:        "Use filesystem.ingest_file to import one approved file into LOOM",
				VersionLabel: version,
				BodyFormat:   capabilities.UsageDocumentFormatMarkdown,
				Body:         "Use `ingest_file` when an actor has already identified one approved safe-root file that should become a LOOM object. The capability reads only that relative path, uploads through the existing node-agent sync/object upload API, and does not perform whole-machine backup or destructive filesystem mutation.",
			},
		},
		Metadata: endpointMetadata(EndpointIngestFile),
	}
}

func summariesForRoots(roots []SafeRoot) []SafeRootSummary {
	summaries := make([]SafeRootSummary, 0, len(roots))
	for _, root := range roots {
		summaries = append(summaries, SafeRootSummary{
			RootKey:              root.RootKey,
			DisplayName:          root.DisplayName,
			AllowList:            root.AllowList,
			AllowMetadata:        root.AllowMetadata,
			AllowIngest:          root.AllowIngest,
			MaxFileBytes:         root.MaxFileBytes,
			IncludeHiddenDefault: root.IncludeHiddenDefault,
			PrivateBackupOnly:    root.PrivateBackupOnly,
			Metadata:             root.Metadata,
		})
	}
	return summaries
}

func rootVisibilityCounts(roots []SafeRoot) (privateBackupOnly int, disabled int) {
	for _, root := range roots {
		if root.PrivateBackupOnly {
			privateBackupOnly++
			continue
		}
		if !root.AllowList && !root.AllowMetadata && !root.AllowIngest {
			disabled++
		}
	}
	return privateBackupOnly, disabled
}

func filesystemManifestJSON(handler, execution string, roots []SafeRootSummary, privateRootCount int) json.RawMessage {
	return mustJSON(map[string]any{
		"source":                         "loom-node-agent",
		"connector":                      ProviderKey,
		"handler":                        ConnectorNamespace + "." + handler,
		"execution":                      execution,
		"addressing":                     "root_key_plus_relative_path",
		"absolute_paths_exposed":         false,
		"safe_root_count":                len(roots),
		"safe_roots":                     roots,
		"private_backup_only_root_count": privateRootCount,
		"slice_enabled":                  true,
	})
}

func endpointMetadata(handler string) json.RawMessage {
	return mustJSON(map[string]any{
		"source":                 "loom-node-agent",
		"connector":              ProviderKey,
		"handler":                ConnectorNamespace + "." + handler,
		"slice":                  "13_part_1",
		"execution":              "remote_node_agent",
		"absolute_paths_exposed": false,
	})
}

func mustJSON(values map[string]any) json.RawMessage {
	data, err := json.Marshal(values)
	if err != nil {
		return json.RawMessage(`{}`)
	}
	return data
}
