package repostate

// SchemaV1 returns a fresh copy of the frozen v1 contract. Callers may inspect
// or transform the returned slices without changing package-global state.
func SchemaV1() Contract {
	return Contract{
		RootPaths: []PathSchema{
			{Pattern: ".repo/repo.yaml", Requirement: PathRequired, Purpose: "repository identity, owner backlink, role, branches, and portable source policy"},
			{Pattern: ".repo/README.md", Requirement: PathRequired, Purpose: "control-plane read order and source-of-truth boundaries"},
			{Pattern: ".repo/REPOSITORY.md", Requirement: PathRequired, Purpose: "repository purpose, architecture entry points, validation, and operational constraints"},
			{Pattern: ".repo/STATE.md", Requirement: PathRequired, Purpose: "current_state, active_focus, recent_outcomes, and blockers declarations"},
			{Pattern: ".repo/ROADMAP.md", Requirement: PathRequired, Purpose: "next_priorities and longer-horizon declarations"},
			{Pattern: ".repo/future/<slug>/", Requirement: PathOptional, Purpose: "unaccepted repository possibilities"},
			{Pattern: ".repo/initiatives/<slug>/", Requirement: PathOptional, Purpose: "broad repository objectives"},
			{Pattern: ".repo/features/<slug>/", Requirement: PathOptional, Purpose: "bounded implementation outcomes"},
			{Pattern: ".repo/decisions/<decision-id>/", Requirement: PathOptional, Purpose: "durable repository decisions"},
			{Pattern: ".repo/releases/<version>/", Requirement: PathOptional, Purpose: "delivery milestones that reference features"},
			{Pattern: ".repo/integrations/", Requirement: PathOptional, Purpose: "portable integration evidence and status"},
			{Pattern: ".repo/architecture/", Requirement: PathOptional, Purpose: "internal repository architecture"},
			{Pattern: ".repo/protocols/", Requirement: PathOptional, Purpose: "repository and harness-boundary workflow rules"},
			{Pattern: ".repo/templates/", Requirement: PathOptional, Purpose: "reviewable source templates for repository objects"},
			{Pattern: ".repo/archive/", Requirement: PathOptional, Purpose: "imported or deliberately retired history"},
		},
		LifecycleSchemas: []LifecycleSchema{
			{
				Kind: ObjectKindFuture, SchemaVersion: "repo.future.v1",
				ManifestPattern: ".repo/future/<slug>/future.yaml", StableIDPattern: "future/<slug>",
				RequiredFields:  []string{"kind", "schema_version", "id", "slug", "title", "status", "created_at", "updated_at"},
				OptionalFields:  []string{"related_initiative", "related_features"},
				AllowedStatuses: []string{"captured", "promoted", "deferred", "cancelled"},
				RequiredFiles:   []string{"future.yaml", "outline.md"},
			},
			{
				Kind: ObjectKindInitiative, SchemaVersion: "repo.initiative.v1",
				ManifestPattern: ".repo/initiatives/<slug>/initiative.yaml", StableIDPattern: "initiative/<slug>",
				RequiredFields:  []string{"kind", "schema_version", "id", "slug", "title", "status", "created_at", "updated_at"},
				OptionalFields:  []string{"features", "future", "releases"},
				AllowedStatuses: []string{"exploring", "active", "achieved", "deferred", "cancelled"},
				RequiredFiles:   []string{"initiative.yaml", "overview.md"},
			},
			{
				Kind: ObjectKindFeature, SchemaVersion: "repo.feature.v1",
				ManifestPattern: ".repo/features/<slug>/feature.yaml", StableIDPattern: "feature/<slug>",
				RequiredFields:   []string{"kind", "schema_version", "id", "slug", "title", "status", "priority", "created_at", "updated_at", "dependencies"},
				OptionalFields:   []string{"initiative", "target_release", "next_action", "blocked_reason"},
				AllowedStatuses:  []string{"discovery", "planned", "ready", "in_progress", "review", "integrated", "validated", "deferred", "cancelled"},
				RequiredFiles:    []string{"feature.yaml", "overview.md", "implementation_slices.md", "worktree_progress.md"},
				ConditionalFiles: []string{"handoff.md required from review onward", "acceptance.md required from integrated onward"},
			},
			{
				Kind: ObjectKindDecision, SchemaVersion: "repo.decision.v1",
				ManifestPattern: ".repo/decisions/<decision-id>/decision.yaml", StableIDPattern: "decision/<ADR-NNNN>",
				RequiredFields:  []string{"kind", "schema_version", "id", "decision_id", "title", "status", "date"},
				OptionalFields:  []string{"owners", "related_features", "supersedes"},
				AllowedStatuses: []string{"proposed", "accepted", "superseded", "rejected"},
				RequiredFiles:   []string{"decision.yaml", "decision.md"},
			},
			{
				Kind: ObjectKindRelease, SchemaVersion: "repo.release.v1",
				ManifestPattern: ".repo/releases/<version>/release.yaml", StableIDPattern: "release/<version>",
				RequiredFields:   []string{"kind", "schema_version", "id", "version", "status", "objective", "features", "created_at", "updated_at"},
				OptionalFields:   []string{"target_date"},
				AllowedStatuses:  []string{"planning", "committed", "in_progress", "acceptance", "released", "deferred", "cancelled"},
				RequiredFiles:    []string{"release.yaml", "overview.md"},
				ConditionalFiles: []string{"acceptance.md required from acceptance onward"},
			},
		},
		CompatibilityMap: []CompatibilityEntry{
			{ProjectSource: ".project/project.yaml#project", RepoTarget: ".repo/repo.yaml#repository + #owner_project", Disposition: DispositionSplit, Rule: "repository identity moves to repository; LOOM project identity and policy remain authoritative in .loom"},
			{ProjectSource: ".project/project.yaml#branches", RepoTarget: ".repo/repo.yaml#branches", Disposition: DispositionSplit, Rule: "retain stable/default branch declarations only; worker prefixes belong to protocols"},
			{ProjectSource: ".project/project.yaml#worktrees", RepoTarget: "none", Disposition: DispositionDrop, Rule: "harness provider and worktree state are runtime concerns; only ownership invariants enter protocols"},
			{ProjectSource: ".project/project.yaml#paths", RepoTarget: "none", Disposition: DispositionDrop, Rule: "v1 state root is fixed at .repo and host/runtime paths are forbidden"},
			{ProjectSource: ".project/project.yaml#commands", RepoTarget: ".repo/REPOSITORY.md + .repo/protocols/", Disposition: DispositionSplit, Rule: "portable validation guidance remains human-authored; it is not repository identity"},
			{ProjectSource: ".project/project.yaml#authority", RepoTarget: ".loom policy + harness authorization", Disposition: DispositionDrop, Rule: "repository declarations do not grant deploy, merge, production, or mutation authority"},
			{ProjectSource: ".project/PROJECT.md", RepoTarget: ".repo/REPOSITORY.md", Disposition: DispositionRename, Rule: "rewrite project-scoped language as repository-scoped guidance"},
			{ProjectSource: ".project/README.md", RepoTarget: ".repo/README.md", Disposition: DispositionPreserve, Rule: "preserve read order and source hierarchy with repository terminology"},
			{ProjectSource: ".project/STATE.md", RepoTarget: ".repo/STATE.md", Disposition: DispositionPreserve, Rule: "preserve concise current state; freeze discovery headings in the v1 pack"},
			{ProjectSource: ".project/ROADMAP.md", RepoTarget: ".repo/ROADMAP.md", Disposition: DispositionPreserve, Rule: "preserve horizon and priority semantics"},
			{ProjectSource: ".project/future/INDEX.md", RepoTarget: ".repo/future/README.md", Disposition: DispositionRename, Rule: "the index is derived navigation and never owns lifecycle"},
			{ProjectSource: ".project/future/<slug>/outline.md", RepoTarget: ".repo/future/<slug>/{future.yaml,outline.md}", Disposition: DispositionSplit, Rule: "move lifecycle metadata to a versioned manifest and preserve narrative"},
			{ProjectSource: ".project/initiatives/README.md", RepoTarget: ".repo/initiatives/README.md", Disposition: DispositionPreserve, Rule: "preserve collection guidance"},
			{ProjectSource: ".project/initiatives/<slug>/overview.md", RepoTarget: ".repo/initiatives/<slug>/{initiative.yaml,overview.md}", Disposition: DispositionSplit, Rule: "move lifecycle and relationships to a versioned manifest and preserve narrative"},
			{ProjectSource: ".project/initiatives/<slug>/<other-files>", RepoTarget: ".repo/initiatives/<slug>/<other-files>", Disposition: DispositionPreserve, Rule: "after the dedicated overview rule, preserve every other initiative-local tracked regular file as a portable attachment without assigning it manifest or lifecycle semantics"},
			{ProjectSource: ".project/features/README.md", RepoTarget: ".repo/features/README.md", Disposition: DispositionPreserve, Rule: "preserve stable-folder guidance"},
			{ProjectSource: ".project/features/<slug>/feature.yaml", RepoTarget: ".repo/features/<slug>/feature.yaml", Disposition: DispositionPreserve, Rule: "add kind-specific schema version and deterministic feature/<slug> id during explicit migration"},
			{ProjectSource: ".project/features/<slug>/overview.md", RepoTarget: ".repo/features/<slug>/overview.md", Disposition: DispositionPreserve, Rule: "preserve accepted narrative scope"},
			{ProjectSource: ".project/features/<slug>/implementation_slices.md", RepoTarget: ".repo/features/<slug>/implementation_slices.md", Disposition: DispositionPreserve, Rule: "preserve slice boundaries and validation gates"},
			{ProjectSource: ".project/features/<slug>/worktree_progress.md", RepoTarget: ".repo/features/<slug>/worktree_progress.md", Disposition: DispositionSplit, Rule: "preserve portable branch/checkpoint/test state; drop absolute paths and harness session identifiers"},
			{ProjectSource: ".project/features/<slug>/handoff.md", RepoTarget: ".repo/features/<slug>/handoff.md", Disposition: DispositionSplit, Rule: "preserve portable handoff evidence; drop absolute paths, session identifiers, and runtime cleanup state"},
			{ProjectSource: ".project/features/<slug>/acceptance*.md", RepoTarget: ".repo/features/<slug>/acceptance.md or named evidence", Disposition: DispositionPreserve, Rule: "preserve source-versioned acceptance evidence without production secrets"},
			{ProjectSource: ".project/features/<slug>/<other-files>", RepoTarget: ".repo/features/<slug>/<other-files>", Disposition: DispositionPreserve, Rule: "preserve feature-local investigations, contracts, and evidence as portable attachments"},
			{ProjectSource: ".project/decisions/README.md", RepoTarget: ".repo/decisions/README.md", Disposition: DispositionPreserve, Rule: "preserve collection guidance"},
			{ProjectSource: ".project/decisions/ADR-NNNN-<slug>.md", RepoTarget: ".repo/decisions/ADR-NNNN/{decision.yaml,decision.md}", Disposition: DispositionSplit, Rule: "move lifecycle metadata to a manifest while retaining the ADR number as stable identity"},
			{ProjectSource: ".project/releases/README.md", RepoTarget: ".repo/releases/README.md", Disposition: DispositionPreserve, Rule: "preserve collection and lifecycle guidance"},
			{ProjectSource: ".project/releases/<version>/release.yaml", RepoTarget: ".repo/releases/<version>/release.yaml", Disposition: DispositionPreserve, Rule: "add kind-specific schema version and deterministic release/<version> id during explicit migration"},
			{ProjectSource: ".project/releases/<version>/overview.md", RepoTarget: ".repo/releases/<version>/overview.md", Disposition: DispositionPreserve, Rule: "preserve release narrative without copying feature plans"},
			{ProjectSource: ".project/releases/<version>/acceptance*.md", RepoTarget: ".repo/releases/<version>/acceptance.md or named evidence", Disposition: DispositionPreserve, Rule: "preserve release-level acceptance evidence"},
			{ProjectSource: ".project/integration/STATUS.md", RepoTarget: ".repo/integrations/STATUS.md", Disposition: DispositionRename, Rule: "pluralize the collection and retain only portable branch, commit, validation, and review state"},
			{ProjectSource: ".project/architecture/README.md", RepoTarget: ".repo/architecture/README.md", Disposition: DispositionPreserve, Rule: "preserve architecture collection guidance"},
			{ProjectSource: ".project/architecture/*.md", RepoTarget: ".repo/architecture/*.md", Disposition: DispositionPreserve, Rule: "preserve repository architecture and documentation indexes"},
			{ProjectSource: ".project/architecture/external-constraints/**", RepoTarget: ".repo/architecture/external-constraints/**", Disposition: DispositionPreserve, Rule: "preserve source-cited external constraints"},
			{ProjectSource: ".project/protocols/PROJECT_STATE_PROTOCOL.md", RepoTarget: ".repo/protocols/REPOSITORY_STATE_PROTOCOL.md", Disposition: DispositionRename, Rule: "rewrite ownership from LOOM project scope to repository scope"},
			{ProjectSource: ".project/protocols/AI_WORKTREE_WORKFLOW.md", RepoTarget: ".repo/protocols/{WORKTREE_OWNERSHIP.md,CODEX_WORKFLOW.md,ORCA_WORKFLOW.md}", Disposition: DispositionSplit, Rule: "keep one-owner-per-worktree invariant and delegate concrete operations to native installed harness skills"},
			{ProjectSource: ".project/protocols/SLICE_AUTOPILOT_PROTOCOL.md", RepoTarget: ".repo/protocols/SLICE_AUTOPILOT_PROTOCOL.md", Disposition: DispositionPreserve, Rule: "preserve harness-neutral slice gates"},
			{ProjectSource: ".project/protocols/CODE_REVIEW_PROTOCOL.md", RepoTarget: ".repo/protocols/CODE_REVIEW_PROTOCOL.md", Disposition: DispositionPreserve, Rule: "preserve review contract"},
			{ProjectSource: ".project/protocols/DOCS_WRITING_PROTOCOL.md", RepoTarget: ".repo/protocols/DOCS_WRITING_PROTOCOL.md", Disposition: DispositionPreserve, Rule: "preserve repository documentation-writing contract"},
			{ProjectSource: ".project/templates/decision.md", RepoTarget: ".repo/templates/decision/", Disposition: DispositionSplit, Rule: "add decision.yaml beside the narrative template"},
			{ProjectSource: ".project/templates/docs/**", RepoTarget: ".repo/templates/docs/**", Disposition: DispositionPreserve, Rule: "preserve public-document authoring templates"},
			{ProjectSource: ".project/templates/future/**", RepoTarget: ".repo/templates/future/**", Disposition: DispositionSplit, Rule: "separate lifecycle manifest from narrative outline"},
			{ProjectSource: ".project/templates/initiative/**", RepoTarget: ".repo/templates/initiative/**", Disposition: DispositionSplit, Rule: "separate lifecycle manifest from narrative overview"},
			{ProjectSource: ".project/templates/feature/**", RepoTarget: ".repo/templates/feature/**", Disposition: DispositionPreserve, Rule: "add stable id/schema fields and remove runtime-only path/session fields"},
			{ProjectSource: ".project/templates/release/**", RepoTarget: ".repo/templates/release/**", Disposition: DispositionPreserve, Rule: "add stable id/schema fields while preserving release composition"},
			{ProjectSource: ".project/archive/{README.md,PATH_MIGRATION.md}", RepoTarget: ".repo/archive/", Disposition: DispositionArchive, Rule: "retain as historical migration context, never current scope"},
			{ProjectSource: ".project/archive/<imported-trees>/**", RepoTarget: ".repo/archive/<imported-trees>/**", Disposition: DispositionArchive, Rule: "retain imported history byte-for-byte when portable and safe"},
		},
		DiscoveryFields: []DiscoveryField{
			{Name: "name", ValueShape: "string", PrimaryPosture: PostureDeclared, Source: ".repo/repo.yaml#repository.name", AllowedPostures: declaredStates(), Rule: "human repository name"},
			{Name: "aliases", ValueShape: "[]string", PrimaryPosture: PostureDeclared, Source: ".repo/repo.yaml#repository.aliases", AllowedPostures: declaredStates(), Rule: "trimmed, case-fold unique aliases sorted by UTF-8 bytes"},
			{Name: "owning_project", ValueShape: "object{id:string,slug:string}", PrimaryPosture: PostureDeclared, Source: ".repo/repo.yaml#owner_project", AllowedPostures: declaredStates(), Rule: "declared backlink; validity is qualified separately against authoritative membership"},
			{Name: "role", ValueShape: "enum{primary,component}", PrimaryPosture: PostureDeclared, Source: ".repo/repo.yaml#repository.role", AllowedPostures: declaredStates(), Rule: "primary or component in the owning project; reference is not a self role"},
			{Name: "purpose", ValueShape: "string", PrimaryPosture: PostureDeclared, Source: ".repo/repo.yaml#repository.purpose", AllowedPostures: declaredStates(), Rule: "short repository-owned purpose"},
			{Name: "topics", ValueShape: "[]string", PrimaryPosture: PostureDeclared, Source: ".repo/repo.yaml#repository.topics", AllowedPostures: declaredStates(), Rule: "lowercase unique topics sorted by UTF-8 bytes"},
			{Name: "current_state", ValueShape: "string", PrimaryPosture: PostureDeclared, Source: ".repo/STATE.md#Current State", AllowedPostures: declaredStates(), Rule: "bounded declared summary, not accepted semantic truth"},
			{Name: "active_focus", ValueShape: "[]string", PrimaryPosture: PostureDeclared, Source: ".repo/STATE.md#Active Focus", AllowedPostures: declaredStates(), Rule: "ordered declared focus items"},
			{Name: "recent_outcomes", ValueShape: "[]string", PrimaryPosture: PostureDeclared, Source: ".repo/STATE.md#Recent Outcomes", AllowedPostures: declaredStates(), Rule: "ordered declared outcomes with source references retained"},
			{Name: "next_priorities", ValueShape: "[]string", PrimaryPosture: PostureDeclared, Source: ".repo/ROADMAP.md#Next Priorities", AllowedPostures: declaredStates(), Rule: "ordered declared priorities"},
			{Name: "blockers", ValueShape: "[]string", PrimaryPosture: PostureDeclared, Source: ".repo/STATE.md#Blockers", AllowedPostures: declaredStates(), Rule: "ordered declared blockers"},
			{Name: "navigation_path", ValueShape: "string", PrimaryPosture: PostureDerived, Source: ".loom/contracts/repos.yaml member path", AllowedPostures: derivedStates(), Rule: "project-relative slash path only; host-absolute resolution is transport-local and not persisted"},
			{Name: "tracking_status", ValueShape: "TrackingStatus", PrimaryPosture: PostureDerived, Source: "non-mutating schema and membership validation", AllowedPostures: []SourcePosture{PostureDerived, PostureInvalid, PostureStale}, Rule: "one frozen TrackingStatus value"},
			{Name: "source_digest", ValueShape: "sha256:<64-lowercase-hex>", PrimaryPosture: PostureDerived, Source: "canonical ordered tracked .repo source set", AllowedPostures: derivedStates(), Rule: "digest follows SourceDigestPolicy and is derived without rewriting source"},
			{Name: "source_commit", ValueShape: "full lowercase Git object ID", PrimaryPosture: PostureObserved, Source: "bounded Git observation", AllowedPostures: observedStates(), Rule: "commit ID observed from Git; never copied from a declaration"},
			{Name: "freshness", ValueShape: "FreshnessPolicy.ValueShape", PrimaryPosture: PostureDerived, Source: "declared updated dates plus bounded Git observation", AllowedPostures: []SourcePosture{PostureDerived, PostureMissing, PostureStale, PostureInvalid}, Rule: "structured observation facts and stale reasons; no unqualified fresh/accepted claim"},
		},
		SourceDigestPolicy: SourceDigestPolicy{
			Algorithm: "SHA-256",
			InputSet:  "all Git-tracked regular-file entries beneath .repo in the extracted source view; untracked files and files outside .repo are excluded; symlinks, submodules, and other non-regular Git entries are malformed",
			Ordering:  "ascending repository-relative slash path by raw UTF-8 bytes",
			Framing:   "ASCII domain 'loom.repo.source.v1\\x00', then for each file uint64be(path byte length), path bytes, uint64be(Git mode byte length), six-digit ASCII Git mode, uint64be(content byte length), and exact blob bytes",
			Output:    "sha256:<64 lowercase hexadecimal digits>",
		},
		FreshnessPolicy: FreshnessPolicy{
			ValueShape:   "object{observed_at:RFC3339Nano,head_commit:string,source_commit:string,latest_repo_commit_at:RFC3339Nano,age_seconds:uint64,tracked_state:enum,reasons:[]string}",
			TrackedState: []string{"clean", "dirty", "unavailable"},
			StaleReasons: []string{"declared_date_after_observation", "git_observation_unavailable", "repo_tree_dirty", "source_commit_not_head", "unsupported_schema"},
			Rule:         "age_seconds is observed_at minus latest_repo_commit_at clamped at zero; reasons are unique and UTF-8 byte sorted; no age threshold or semantic acceptance is inferred",
		},
		MembershipRules: []MembershipRule{
			{Code: "state_root_absent", Status: TrackingNotEnabled, Precedence: 1, Rule: "an absent .repo directory is valid project membership with repository-state tracking disabled"},
			{Code: "manifest_envelope_malformed", Status: TrackingMalformed, Precedence: 2, Rule: "missing repo.yaml, invalid YAML, or a missing/invalid kind or schema_version envelope is malformed"},
			{Code: "schema_unsupported", Status: TrackingStaleVersion, Precedence: 3, Rule: "a readable envelope with an unsupported exact schema version is stale; its version-specific body is not interpreted or rewritten"},
			{Code: "manifest_body_malformed", Status: TrackingMalformed, Precedence: 4, Rule: "for a supported version, unknown fields, invalid typed IDs, unsafe values, non-regular Git entries, or forbidden portable data are malformed"},
			{Code: "owner_membership_unresolved", Status: TrackingMembershipUnresolved, Precedence: 5, Rule: "validation cannot return valid until the authoritative owning membership is available; a reference membership alone is not an owner claim"},
			{Code: "repository_id_mismatch", Status: TrackingMismatchedRepository, Precedence: 6, Rule: "repo.yaml repository.id must exactly equal the authoritative repository member ID"},
			{Code: "owner_project_mismatch", Status: TrackingMismatchedOwner, Precedence: 7, Rule: "repo.yaml owner_project.id and owner_project.slug must both exactly equal the authoritative owning project; an ID match never excuses a stale slug"},
			{Code: "owner_role_mismatch", Status: TrackingMismatchedMembership, Precedence: 8, Rule: "repo.yaml role must exactly equal the owning membership role and must be primary or component; reference memberships from other projects do not replace it"},
			{Code: "state_root_mismatch", Status: TrackingMismatchedMembership, Precedence: 9, Rule: "the authoritative owning member state_root must resolve to .repo; empty means .repo and any other value is a mismatch for v1"},
			{Code: "membership_valid", Status: TrackingValid, Precedence: 10, Rule: "identity, owner backlink, owning role, and state root all match authoritative membership"},
		},
		VersionPolicy: VersionPolicy{
			SupportedRepositoryVersions: []string{RepositorySchemaVersion},
			CompatibilityRule:           "support is an explicit exact-version allowlist; v1 has no implicit minor-version negotiation",
			UnknownVersionRule:          "return stale_version after reading only the kind/schema envelope; do not extract or rewrite object content",
			ChangeRule:                  "any field, required-file, lifecycle, normalization, or semantic rule change creates a new immutable schema version",
			UpgradeRule:                 "validation is read-only; upgrades occur only through a separately reviewed explicit migration plan",
			UnknownFieldRule:            "unknown manifest fields are malformed under v1 so misspellings and silent semantic drift fail closed",
		},
		PortableTrackingRules: []string{
			"every portable file below .repo is Git-tracked source",
			"empty directories are not required and are materialized only by tracked content",
			"validation and extraction do not add, delete, rewrite, stage, or commit files",
			"declared lists use their schema-defined ordering; canonical digests sort source paths by UTF-8 bytes without changing files",
			"all committed paths and navigation paths use slash-separated repository- or project-relative form",
			"Git commits and dirty state are observations, never declarations stored in repo.yaml",
		},
		ForbiddenPortableData: []string{
			"absolute host or worktree paths",
			"Codex, ORCA, terminal, or conversation session identifiers",
			"runtime caches, locks, sockets, logs, generated indexes, or mutable state directories",
			"Git symlinks, submodules, or any non-regular entry beneath .repo",
			"credentials, secret values, environment files, authentication material, or credential-store exports",
			"private agent memory, personality, hidden prompts, or harness state",
			"claims that a declaration or Git observation is accepted semantic context",
		},
		AcceptedContextRule: "deterministic extraction always emits accepted_context as empty; only the later Provenance layer may join accepted semantic records",
	}
}

func declaredStates() []SourcePosture {
	return []SourcePosture{PostureDeclared, PostureMissing, PostureStale, PostureInvalid}
}

func observedStates() []SourcePosture {
	return []SourcePosture{PostureObserved, PostureMissing, PostureStale, PostureInvalid}
}

func derivedStates() []SourcePosture {
	return []SourcePosture{PostureDerived, PostureMissing, PostureStale, PostureInvalid}
}
