#!/usr/bin/env sh
set -eu

if [ -z "${LOOM_INPUT_OBJECT_PATH:-}" ]; then
  echo "LOOM_INPUT_OBJECT_PATH is required" >&2
  exit 1
fi

if [ -z "${LOOM_ARTIFACT_DIR:-}" ]; then
  echo "LOOM_ARTIFACT_DIR is required" >&2
  exit 1
fi

if [ -z "${LOOM_RESULT_FILE:-}" ]; then
  echo "LOOM_RESULT_FILE is required" >&2
  exit 1
fi

word_count="$(wc -w < "$LOOM_INPUT_OBJECT_PATH" | tr -d ' ')"
token_line="$(grep -m 1 'slicefiveartifact' "$LOOM_INPUT_OBJECT_PATH" || true)"

mkdir -p "$LOOM_ARTIFACT_DIR/artifacts"

{
  echo "# Word Count Report"
  echo
  echo "Slice 5 artifact report generated by LOOM."
  echo
  echo "Word count: $word_count"
  echo
  if [ -n "$token_line" ]; then
    echo "$token_line"
  fi
} > "$LOOM_ARTIFACT_DIR/artifacts/report.md"

echo "counted $word_count words"
echo "diagnostic: stderr captured" >&2

printf '{"status":"ok","outputs":{"word_count":%s},"artifacts":[{"key":"report","path":"artifacts/report.md","type":"report","title":"Word Count Report"}]}\n' "$word_count" > "$LOOM_RESULT_FILE"
